FROM registry.cn-beijing.aliyuncs.com/yunionio/onecloud-base:v0.2

LABEL maintainer="Qu Xuan <quxuan@yunion.com>"

# install default playbook and install pkg
RUN mkdir -p /opt/yunion/ansible-install-pkg

COPY build/dist/telegraf*.deb /opt/yunion/ansible-install-pkg
COPY build/dist/telegraf*.rpm /opt/yunion/ansible-install-pkg
COPY build/dist/telegraf*.zip /opt/yunion/ansible-install-pkg
