BUILD_DIR = $(CURDIR)/build
CONTAINER_GO_DIR = /go
CONTAINER_TELEGRAF_DIR = $(CONTAINER_GO_DIR)/src/github.com/influxdata/telegraf

container-packages:
	docker run --rm \
		--name docker-telegraf-build \
		-v $(CURDIR):$(CONTAINER_TELEGRAF_DIR) \
		-v $(BUILD_DIR)/go/pkg:$(CONTAINER_GO_DIR)/pkg \
		registry.cn-beijing.aliyuncs.com/yunionio/telegraf-ci:1.16.6 \
		/bin/bash -c "cd $(CONTAINER_TELEGRAF_DIR) && make deps && make package amd64=1 arm64=1"
