FROM registry.cn-beijing.aliyuncs.com/yunionio/onecloud-base:v0.2

MAINTAINER "YaoQi Wan <wanyaoqi@yunionyun.com>"

ENV TZ Asia/Shanghai

RUN apk update && \
    apk add --no-cache tzdata ca-certificates ntpsec && \
    rm -rf /var/cache/apk/*

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p /usr/bin
ADD ./telegraf /usr/bin/telegraf

RUN mkdir -p /etc/telegraf/telegraf.d
RUN mkdir -p /etc/logrotate.d
ADD ./etc/logrotate.d/telegraf /etc/logrotated.d/telegraf
